version: '2'
services:
  backend:
    image: docker.io/pgore/backend
    build:
      context: ./backend
  gateway:
    image: docker.io/pgore/gateway
    build:
      context: ./gateway
    ports:
      - "1111:1111"
  daily:
    image: docker.io/pgore/daily-backend
    build:
      context: ./daily-backend
