apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: daily
  name: daily
spec:
  replicas: 1
  selector:
    io.kompose.service: daily
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: daily
    spec:
      containers:
      - image: ' '
        name: daily
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - daily
      from:
        kind: ImageStreamTag
        name: daily:latest
    type: ImageChange
status: {}
