apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: daily
  name: daily
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: daily:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: daily-backend/
    git:
      ref: nodejs-service
      uri: https://github.com/pranavgore09/classico.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
  - type: ConfigChange
  - type: ImageChange
status:
  lastVersion: 0
