// Code generated by protoc-gen-go. DO NOT EDIT.
// source: math.proto

/*
Package math is a generated protocol buffer package.

It is generated from these files:
	math.proto

It has these top-level messages:
	Value
	BinaryValue
	UnaryValue
*/
package math

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math1 "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math1.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Value struct {
	R int32 `protobuf:"varint,1,opt,name=r" json:"r,omitempty"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Value) GetR() int32 {
	if m != nil {
		return m.R
	}
	return 0
}

type BinaryValue struct {
	A int32 `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
}

func (m *BinaryValue) Reset()                    { *m = BinaryValue{} }
func (m *BinaryValue) String() string            { return proto.CompactTextString(m) }
func (*BinaryValue) ProtoMessage()               {}
func (*BinaryValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BinaryValue) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *BinaryValue) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type UnaryValue struct {
	A int32 `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
}

func (m *UnaryValue) Reset()                    { *m = UnaryValue{} }
func (m *UnaryValue) String() string            { return proto.CompactTextString(m) }
func (*UnaryValue) ProtoMessage()               {}
func (*UnaryValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UnaryValue) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func init() {
	proto.RegisterType((*Value)(nil), "math.Value")
	proto.RegisterType((*BinaryValue)(nil), "math.BinaryValue")
	proto.RegisterType((*UnaryValue)(nil), "math.UnaryValue")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Addition service

type AdditionClient interface {
	Add(ctx context.Context, in *BinaryValue, opts ...grpc.CallOption) (*Value, error)
	Incr(ctx context.Context, in *UnaryValue, opts ...grpc.CallOption) (*Value, error)
}

type additionClient struct {
	cc *grpc.ClientConn
}

func NewAdditionClient(cc *grpc.ClientConn) AdditionClient {
	return &additionClient{cc}
}

func (c *additionClient) Add(ctx context.Context, in *BinaryValue, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := grpc.Invoke(ctx, "/math.Addition/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *additionClient) Incr(ctx context.Context, in *UnaryValue, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := grpc.Invoke(ctx, "/math.Addition/Incr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Addition service

type AdditionServer interface {
	Add(context.Context, *BinaryValue) (*Value, error)
	Incr(context.Context, *UnaryValue) (*Value, error)
}

func RegisterAdditionServer(s *grpc.Server, srv AdditionServer) {
	s.RegisterService(&_Addition_serviceDesc, srv)
}

func _Addition_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinaryValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdditionServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/math.Addition/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdditionServer).Add(ctx, req.(*BinaryValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Addition_Incr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdditionServer).Incr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/math.Addition/Incr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdditionServer).Incr(ctx, req.(*UnaryValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _Addition_serviceDesc = grpc.ServiceDesc{
	ServiceName: "math.Addition",
	HandlerType: (*AdditionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Addition_Add_Handler,
		},
		{
			MethodName: "Incr",
			Handler:    _Addition_Incr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "math.proto",
}

func init() { proto.RegisterFile("math.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0x2c, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x44, 0xb9, 0x58, 0xc3, 0x12,
	0x73, 0x4a, 0x53, 0x85, 0x78, 0xb8, 0x18, 0x8b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x18,
	0x8b, 0x94, 0x34, 0xb9, 0xb8, 0x9d, 0x32, 0xf3, 0x12, 0x8b, 0x2a, 0xe1, 0x92, 0x89, 0x30, 0xc9,
	0x44, 0x10, 0x2f, 0x49, 0x82, 0x09, 0xc2, 0x4b, 0x52, 0x92, 0xe2, 0xe2, 0x0a, 0xc5, 0xa1, 0xd2,
	0x28, 0x86, 0x8b, 0xc3, 0x31, 0x25, 0x25, 0xb3, 0x24, 0x33, 0x3f, 0x4f, 0x48, 0x9d, 0x8b, 0xd9,
	0x31, 0x25, 0x45, 0x48, 0x50, 0x0f, 0xec, 0x06, 0x24, 0xd3, 0xa5, 0xb8, 0x21, 0x42, 0x60, 0x8e,
	0x12, 0x83, 0x90, 0x3a, 0x17, 0x8b, 0x67, 0x5e, 0x72, 0x91, 0x90, 0x00, 0x44, 0x38, 0x14, 0x97,
	0xc2, 0x24, 0x36, 0xb0, 0x47, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xf8, 0x76, 0x71,
	0xd6, 0x00, 0x00, 0x00,
}
