// Code generated by protoc-gen-go. DO NOT EDIT.
// source: daily.proto

/*
Package daily is a generated protocol buffer package.

It is generated from these files:
	daily.proto

It has these top-level messages:
	Text
*/
package daily

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Text struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *Text) Reset()                    { *m = Text{} }
func (m *Text) String() string            { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()               {}
func (*Text) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Text)(nil), "daily.Text")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Starwars service

type StarwarsClient interface {
	GetQuote(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Text, error)
}

type starwarsClient struct {
	cc *grpc.ClientConn
}

func NewStarwarsClient(cc *grpc.ClientConn) StarwarsClient {
	return &starwarsClient{cc}
}

func (c *starwarsClient) GetQuote(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Text, error) {
	out := new(Text)
	err := grpc.Invoke(ctx, "/daily.Starwars/GetQuote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Starwars service

type StarwarsServer interface {
	GetQuote(context.Context, *Text) (*Text, error)
}

func RegisterStarwarsServer(s *grpc.Server, srv StarwarsServer) {
	s.RegisterService(&_Starwars_serviceDesc, srv)
}

func _Starwars_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Text)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daily.Starwars/GetQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsServer).GetQuote(ctx, req.(*Text))
	}
	return interceptor(ctx, in, info, handler)
}

var _Starwars_serviceDesc = grpc.ServiceDesc{
	ServiceName: "daily.Starwars",
	HandlerType: (*StarwarsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuote",
			Handler:    _Starwars_GetQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daily.proto",
}

func init() { proto.RegisterFile("daily.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x49, 0xcc, 0xcc,
	0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xa4, 0xb8, 0x58, 0x42,
	0x52, 0x2b, 0x4a, 0x84, 0x84, 0xb8, 0x58, 0x4a, 0x52, 0x2b, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0xc0, 0x6c, 0x23, 0x23, 0x2e, 0x8e, 0xe0, 0x92, 0xc4, 0xa2, 0xf2, 0xc4, 0xa2, 0x62,
	0x21, 0x35, 0x2e, 0x0e, 0xf7, 0xd4, 0x92, 0xc0, 0xd2, 0xfc, 0x92, 0x54, 0x21, 0x6e, 0x3d, 0x88,
	0x41, 0x20, 0x8d, 0x52, 0xc8, 0x1c, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xe9, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x5c, 0x8d, 0x2e, 0x6b, 0x6c, 0x00, 0x00, 0x00,
}
